# Generated by Django 4.1 on 2022-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('description', models.TextField(max_length=650)),
                ('genre', models.CharField(choices=[('H', 'Horror'), ('S', 'Scify'), ('A', 'Action'), ('C', 'Comedy'), ('D', 'Drama'), ('R', 'Romance'), ('O', 'Rom Com'), ('T', 'Thriller'), ('M', 'Mystery'), ('F', 'Family')], default='H', max_length=1)),
                ('mpaa_rating', models.CharField(choices=[('G', 'G'), ('P', 'PG'), ('1', 'PG-13'), ('R', 'R'), ('N', 'NC-17'), ('M', 'Mature Audience, Be Advised')], default='G', max_length=1)),
            ],
        ),
    ]
