# Generated by Django 4.1 on 2022-09-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mpaa_rating',
            field=models.CharField(choices=[('G', 'G'), ('P', 'PG'), ('1', 'PG-13'), ('R', 'R'), ('N', 'NC-17'), ('M', 'Mature Audience, Be Advised'), ('O', 'Not Rated')], default='G', max_length=1),
        ),
    ]
