# Generated by Django 4.1 on 2022-09-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_media_mpaa_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_watched', models.DateField()),
                ('continue_watching', models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], max_length=1)),
                ('completed_watching', models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], max_length=1)),
                ('would_watch_again', models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], max_length=1)),
                ('movie', models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
