# Generated by Django 4.1 on 2022-09-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_journal_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='where_am_i_watching',
            field=models.CharField(choices=[('N', 'Netflix'), ('A', 'Amazon Prime'), ('D', 'Disney'), ('F', 'Funimation'), ('H', 'Hulu'), ('B', 'HBO Max'), ('P', 'Peacock'), ('C', 'Crunchyroll'), ('M', 'Paramount+'), ('T', 'Apple TV+')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='amazon_prime',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='apple_tv_plus',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='crunchyroll',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='disney_plus',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='funimation',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='hbo_max',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='hulu',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='netflix',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='paramount_plus',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='peacock',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
