# Generated by Django 4.1 on 2022-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_journal_where_am_i_watching_media_amazon_prime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='where_am_i_watching',
            field=models.CharField(choices=[('N', 'Netflix'), ('A', 'Amazon Prime'), ('D', 'Disney'), ('F', 'Funimation'), ('H', 'Hulu'), ('B', 'HBO Max'), ('P', 'Peacock'), ('C', 'Crunchyroll'), ('M', 'Paramount+'), ('T', 'Apple TV+')], default='N', max_length=1),
        ),
    ]
