# Generated by Django 4.1 on 2022-09-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='completed_watching',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='journal',
            name='continue_watching',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='journal',
            name='movie',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='journal',
            name='would_watch_again',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='amazon_prime',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='apple_tv_plus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='crunchyroll',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='disney_plus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='funimation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='hbo_max',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='hulu',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='mpaa_rating',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='netflix',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='paramount_plus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='peacock',
            field=models.BooleanField(),
        ),
    ]
