# Generated by Django 4.1 on 2022-09-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_media_genre_media_action_media_anime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='action',
            new_name='action_genre',
        ),
    ]
