# Generated by Django 4.0.6 on 2022-09-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_media_action_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='amazon_prime',
        ),
        migrations.RemoveField(
            model_name='media',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='media',
            name='apple_tv_plus',
        ),
        migrations.RemoveField(
            model_name='media',
            name='cartoon',
        ),
        migrations.RemoveField(
            model_name='media',
            name='comedy',
        ),
        migrations.RemoveField(
            model_name='media',
            name='crunchyroll',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='disney_plus',
        ),
        migrations.RemoveField(
            model_name='media',
            name='documentary',
        ),
        migrations.RemoveField(
            model_name='media',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='media',
            name='family',
        ),
        migrations.RemoveField(
            model_name='media',
            name='fantasy',
        ),
        migrations.RemoveField(
            model_name='media',
            name='funimation',
        ),
        migrations.RemoveField(
            model_name='media',
            name='hbo_max',
        ),
        migrations.RemoveField(
            model_name='media',
            name='horror',
        ),
        migrations.RemoveField(
            model_name='media',
            name='hulu',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mpaa_rating',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mystery',
        ),
        migrations.RemoveField(
            model_name='media',
            name='netflix',
        ),
        migrations.RemoveField(
            model_name='media',
            name='paramount_plus',
        ),
        migrations.RemoveField(
            model_name='media',
            name='peacock',
        ),
        migrations.RemoveField(
            model_name='media',
            name='romance',
        ),
        migrations.RemoveField(
            model_name='media',
            name='scifi',
        ),
        migrations.RemoveField(
            model_name='media',
            name='thriller',
        ),
    ]
