# Generated by Django 4.1 on 2022-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_media_action_genre_media_amazon_prime_media_anime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='movie',
        ),
        migrations.AddField(
            model_name='journal',
            name='last_episode_watched',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='movie',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
